package genny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String email;
   private java.lang.String password;
   private java.lang.String username;
   private java.lang.String user_type;
   private java.lang.String mobile;
   private java.lang.String fname;
   private java.lang.String lname;

   private java.lang.Boolean status;

   public User()
   {
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getPassword()
   {
      return this.password;
   }

   public void setPassword(java.lang.String password)
   {
      this.password = password;
   }

   public java.lang.String getUsername()
   {
      return this.username;
   }

   public void setUsername(java.lang.String username)
   {
      this.username = username;
   }

   public java.lang.String getUser_type()
   {
      return this.user_type;
   }

   public void setUser_type(java.lang.String user_type)
   {
      this.user_type = user_type;
   }

   public java.lang.String getMobile()
   {
      return this.mobile;
   }

   public void setMobile(java.lang.String mobile)
   {
      this.mobile = mobile;
   }

   public java.lang.String getFname()
   {
      return this.fname;
   }

   public void setFname(java.lang.String fname)
   {
      this.fname = fname;
   }

   public java.lang.String getLname()
   {
      return this.lname;
   }

   public void setLname(java.lang.String lname)
   {
      this.lname = lname;
   }

   public java.lang.Boolean getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.Boolean status)
   {
      this.status = status;
   }

   public User(java.lang.String email, java.lang.String password,
         java.lang.String username, java.lang.String user_type,
         java.lang.String mobile, java.lang.String fname,
         java.lang.String lname, java.lang.Boolean status)
   {
      this.email = email;
      this.password = password;
      this.username = username;
      this.user_type = user_type;
      this.mobile = mobile;
      this.fname = fname;
      this.lname = lname;
      this.status = status;
   }

}