import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QMessage.MessageData;
import io.vertx.rxjava.core.eventbus.EventBus;
import com.google.gson.Gson;

import genny.Json;

rule "Layout 3"
	ruleflow-group "LayoutRules"
	no-loop true
    when
        m : QEventMessage( QEventMessage.getData().getCode().equals("Layout3") )
        bus: EventBus()
    then
        QCmdMessage cmd = new QCmdMessage("CMD_LAYOUT","Layout3");
         Gson gson = new Gson();
        String json = gson.toJson(cmd);
        System.out.println(json);
        bus.publish("cmds", json);        
        System.out.println(m.getData().getCode());
        
        
        // Assigning code to Json data object
        String code= m.getData().getCode();
        Json jsonObject = new Json(code);
end




