package genny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Json implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Json() {
    }

}