package genny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Json implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Json Data")
   private java.lang.String data;

   public Json()
   {
   }

   public java.lang.String getData()
   {
      return this.data;
   }

   public void setData(java.lang.String data)
   {
      this.data = data;
   }

   public Json(java.lang.String data)
   {
      this.data = data;
   }

}