package genny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Email")
   private java.lang.String email;
   @org.kie.api.definition.type.Label(value = "Passworf")
   private java.lang.String password;
   @org.kie.api.definition.type.Label(value = "Mobile")
   private java.lang.String mobile;
   @org.kie.api.definition.type.Label(value = "User Type")
   private java.lang.String userType;

   public User()
   {
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getPassword()
   {
      return this.password;
   }

   public void setPassword(java.lang.String password)
   {
      this.password = password;
   }

   public java.lang.String getMobile()
   {
      return this.mobile;
   }

   public void setMobile(java.lang.String mobile)
   {
      this.mobile = mobile;
   }

   public java.lang.String getUserType()
   {
      return this.userType;
   }

   public void setUserType(java.lang.String userType)
   {
      this.userType = userType;
   }

   public User(java.lang.String email, java.lang.String password,
         java.lang.String mobile, java.lang.String userType)
   {
      this.email = email;
      this.password = password;
      this.mobile = mobile;
      this.userType = userType;
   }

}