package genny;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class QEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String event_type;
   private java.lang.String code;

   public QEvent()
   {
   }

   public java.lang.String getEvent_type()
   {
      return this.event_type;
   }

   public void setEvent_type(java.lang.String event_type)
   {
      this.event_type = event_type;
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public QEvent(java.lang.String event_type, java.lang.String code)
   {
      this.event_type = event_type;
      this.code = code;
   }

}